version: "3"

services:
  mysqldb:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
        - MYSQL_ROOT_PASSWORD=passwd
        - MYSQL_DATABASE=ps23si
        - MYSQL_USER=ps
        - MYSQL_PASSWORD=p@sswd

  spring:
    image: java:latest
    restart: on-failure
    container_name: bootcamp-spring
    depends_on:
      - mysqldb
    ports:
      - 5500:5500
    volumes:
      - ./:/app
    working_dir: /app
    links:
      - mysqldb:mysqldb
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=ps
      - DATABASE_PASSWORD=p@sswd
      - DATABASE_NAME=ps23si
      - DATABASE_PORT=3306
